"""Unified ratings system for Essence Wars.

This module provides a unified interface for tracking and comparing ratings
across both deck performance (from Rust arena) and agent performance (from
Python benchmarks).

Example:
    >>> from essence_wars.ratings import UnifiedRatings
    >>> ratings = UnifiedRatings.load()
    >>> print(ratings.get_leaderboard())
    >>> print(ratings.deck_ratings.get_ranked())
    >>> print(ratings.agent_ratings.get_ranked())

See Also:
    - Deck ratings are generated by: `cargo run --release --bin arena`
    - Agent ratings are generated by: `essence-wars benchmark`
"""

from .agent_ratings import AgentRating, AgentRatings
from .base import BaseRating, RatingCategory
from .deck_ratings import DeckRating, DeckRatings
from .unified import LeaderboardEntry, UnifiedRatings

__all__ = [
    # Base
    "BaseRating",
    "RatingCategory",
    # Deck ratings
    "DeckRatings",
    "DeckRating",
    # Agent ratings
    "AgentRatings",
    "AgentRating",
    # Unified
    "UnifiedRatings",
    "LeaderboardEntry",
]
