"""HTML report generator for Essence Wars.

Generates unified HTML reports with tabs for different data views.
"""

from __future__ import annotations

import shutil
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Environment, FileSystemLoader

from .loaders.validation import ValidationData, load_validation_data
from .tabs.overview import OverviewTab
from .tabs.validation import ValidationTab

if TYPE_CHECKING:
    pass


class ReportGenerator:
    """Generator for unified HTML reports."""

    def __init__(
        self,
        output_dir: Path | str = "reports",
        theme: str = "dark",
    ):
        """Initialize the report generator.

        Args:
            output_dir: Directory to write reports to
            theme: Color theme ("dark" or "light")
        """
        self.output_dir = Path(output_dir)
        self.theme = theme

        # Find template directory
        self.template_dir = Path(__file__).parent.parent.parent.parent / "templates" / "report"
        if not self.template_dir.exists():
            # Fallback to embedded templates
            self.template_dir = None

    def generate_validation_report(
        self,
        run_id: str | None = None,
        validation_dir: Path | str = "experiments/validation",
        tabs: list[str] | None = None,
    ) -> Path:
        """Generate a report for a single validation run.

        Args:
            run_id: Validation run ID ("latest" for most recent)
            validation_dir: Base directory for validation runs
            tabs: List of tabs to include (default: all)

        Returns:
            Path to the generated report
        """
        # Load validation data
        data = load_validation_data(run_id, Path(validation_dir))

        # Determine which tabs to include
        all_tabs = ["overview", "validation"]
        tabs = tabs or all_tabs
        tabs = [t for t in tabs if t in all_tabs]

        # Create output directory
        report_dir = self.output_dir / data.run_id
        report_dir.mkdir(parents=True, exist_ok=True)

        # Generate tab content
        tab_content = {}
        if "overview" in tabs:
            tab_content["overview"] = OverviewTab(data).render()
        if "validation" in tabs:
            tab_content["validation"] = ValidationTab(data).render()

        # Generate HTML
        html = self._render_html(
            title=f"Validation Report - {data.run_id}",
            tab_content=tab_content,
            tabs=tabs,
            data=data,
        )

        # Write files
        output_path = report_dir / "index.html"
        output_path.write_text(html)

        # Write assets
        self._write_assets(report_dir)

        return output_path

    def _render_html(
        self,
        title: str,
        tab_content: dict[str, str],
        tabs: list[str],
        data: ValidationData,
    ) -> str:
        """Render the complete HTML document."""
        # Tab labels
        tab_labels = {
            "overview": "Overview",
            "validation": "Validation",
            "tuning": "Tuning",
            "elo": "ELO Ratings",
        }

        # Build tabs HTML
        tabs_html = []
        for i, tab_id in enumerate(tabs):
            active_class = " active" if i == 0 else ""
            tabs_html.append(
                f'<button class="tab-btn{active_class}" data-tab="{tab_id}">'
                f'{tab_labels.get(tab_id, tab_id.title())}</button>'
            )

        # Build tab panels HTML
        panels_html = []
        for i, tab_id in enumerate(tabs):
            active_class = " active" if i == 0 else ""
            content = tab_content.get(tab_id, "")
            panels_html.append(f'<div class="tab-panel{active_class}" id="{tab_id}-panel">{content}</div>')

        return f"""<!DOCTYPE html>
<html lang="en" data-theme="{self.theme}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <link rel="stylesheet" href="assets/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
</head>
<body>
    <header class="report-header">
        <div class="header-content">
            <h1>Essence Wars</h1>
            <span class="report-type">Balance Report</span>
        </div>
        <div class="header-meta">
            <span class="run-id">{data.run_id}</span>
            <span class="timestamp">{data.timestamp.strftime('%Y-%m-%d %H:%M')}</span>
        </div>
    </header>

    <nav class="tabs">
        {"".join(tabs_html)}
    </nav>

    <main class="content">
        {"".join(panels_html)}
    </main>

    <footer class="report-footer">
        <p>Generated by Essence Wars Report Generator &bull; {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        <p>Version {data.version} ({data.git_hash})</p>
    </footer>

    <script src="assets/report.js"></script>
</body>
</html>
"""

    def _write_assets(self, report_dir: Path) -> None:
        """Write CSS and JS assets to the report directory."""
        assets_dir = report_dir / "assets"
        assets_dir.mkdir(exist_ok=True)

        # Write CSS
        css_path = assets_dir / "styles.css"
        css_path.write_text(self._get_css())

        # Write JS
        js_path = assets_dir / "report.js"
        js_path.write_text(self._get_js())

    def _get_css(self) -> str:
        """Get the CSS styles for the report."""
        return """/* Essence Wars Report Styles */

:root {
    /* Dark theme (default) */
    --bg-primary: #1a1a2e;
    --bg-secondary: #16213e;
    --bg-card: #0f3460;
    --bg-hover: #1f4287;
    --text-primary: #eaeaea;
    --text-secondary: #a0a0a0;
    --border-color: #2a2a4e;
    --accent: #e94560;
    --success: #00d26a;
    --warning: #ffc107;
    --danger: #dc3545;

    /* Faction colors */
    --argentum: #D4AF37;
    --symbiote: #7FFF00;
    --obsidion: #00FFFF;
    --neutral: #B87333;
}

[data-theme="light"] {
    --bg-primary: #f5f5f5;
    --bg-secondary: #ffffff;
    --bg-card: #ffffff;
    --bg-hover: #e8e8e8;
    --text-primary: #1a1a2e;
    --text-secondary: #666666;
    --border-color: #dddddd;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    background-color: var(--bg-primary);
    color: var(--text-primary);
    line-height: 1.6;
    min-height: 100vh;
}

/* Header */
.report-header {
    background: var(--bg-secondary);
    padding: 1.5rem 2rem;
    border-bottom: 2px solid var(--accent);
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.header-content h1 {
    font-size: 1.5rem;
    color: var(--accent);
    font-weight: 700;
}

.report-type {
    color: var(--text-secondary);
    font-size: 0.9rem;
    margin-left: 1rem;
}

.header-meta {
    text-align: right;
    font-size: 0.9rem;
    color: var(--text-secondary);
}

.header-meta .run-id {
    display: block;
    font-family: monospace;
    color: var(--text-primary);
}

/* Tabs */
.tabs {
    background: var(--bg-secondary);
    padding: 0 2rem;
    border-bottom: 1px solid var(--border-color);
    display: flex;
    gap: 0.5rem;
}

.tab-btn {
    background: transparent;
    border: none;
    color: var(--text-secondary);
    padding: 1rem 1.5rem;
    cursor: pointer;
    font-size: 0.95rem;
    font-weight: 500;
    transition: all 0.2s ease;
    border-bottom: 3px solid transparent;
}

.tab-btn:hover {
    color: var(--text-primary);
    background: var(--bg-hover);
}

.tab-btn.active {
    color: var(--accent);
    border-bottom-color: var(--accent);
}

/* Content */
.content {
    padding: 2rem;
    max-width: 1400px;
    margin: 0 auto;
}

.tab-panel {
    display: none;
}

.tab-panel.active {
    display: block;
}

/* Metrics Grid */
.metrics-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
    margin-bottom: 2rem;
}

.metric-card {
    background: var(--bg-card);
    border-radius: 8px;
    padding: 1.5rem;
    display: flex;
    align-items: center;
    gap: 1rem;
    border: 1px solid var(--border-color);
}

.metric-card.wide {
    grid-column: span 2;
    justify-content: center;
}

.metric-icon {
    font-size: 2rem;
    color: var(--accent);
}

.metric-value {
    font-size: 1.75rem;
    font-weight: 700;
}

.metric-title {
    color: var(--text-secondary);
    font-size: 0.85rem;
}

.metric-card.status-success .metric-value { color: var(--success); }
.metric-card.status-warning .metric-value { color: var(--warning); }
.metric-card.status-balanced .metric-value { color: var(--success); }

/* Charts */
.charts-row {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 1.5rem;
    margin-bottom: 2rem;
}

.chart-card, .chart-section {
    background: var(--bg-card);
    border-radius: 8px;
    padding: 1rem;
    border: 1px solid var(--border-color);
}

.chart-section h3 {
    margin-bottom: 1rem;
    color: var(--text-primary);
}

.chart-container {
    min-height: 300px;
}

/* Warnings */
.warnings-section {
    background: rgba(255, 193, 7, 0.1);
    border: 1px solid var(--warning);
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 2rem;
}

.warnings-section h3, .warnings-section h4 {
    color: var(--warning);
    margin-bottom: 1rem;
}

.warning-item {
    padding: 0.5rem 0;
    border-bottom: 1px solid rgba(255, 193, 7, 0.2);
}

.outlier-list {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-top: 0.5rem;
}

.outlier-item {
    background: var(--bg-card);
    padding: 0.5rem 1rem;
    border-radius: 4px;
    display: flex;
    align-items: center;
    gap: 0.75rem;
}

.outlier-item.high { border-left: 3px solid var(--danger); }
.outlier-item.low { border-left: 3px solid var(--warning); }

/* Tables */
.table-section {
    background: var(--bg-card);
    border-radius: 8px;
    padding: 1.5rem;
    border: 1px solid var(--border-color);
    margin-bottom: 2rem;
}

.table-section h3 {
    margin-bottom: 1rem;
}

.table-wrapper {
    overflow-x: auto;
}

.deck-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.9rem;
}

.deck-table th, .deck-table td {
    padding: 0.75rem 1rem;
    text-align: left;
    border-bottom: 1px solid var(--border-color);
}

.deck-table th {
    background: var(--bg-secondary);
    font-weight: 600;
    color: var(--text-secondary);
    text-transform: uppercase;
    font-size: 0.75rem;
    letter-spacing: 0.5px;
}

.deck-table tr:hover {
    background: var(--bg-hover);
}

.deck-cell .commander-name {
    font-weight: 600;
    display: block;
}

.deck-cell .deck-id {
    color: var(--text-secondary);
    font-size: 0.8rem;
}

/* Faction badges */
.faction-badge {
    display: inline-block;
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
}

.faction-argentum { background: rgba(212, 175, 55, 0.2); color: var(--argentum); }
.faction-symbiote { background: rgba(127, 255, 0, 0.2); color: var(--symbiote); }
.faction-obsidion { background: rgba(0, 255, 255, 0.2); color: var(--obsidion); }
.faction-neutral { background: rgba(184, 115, 51, 0.2); color: var(--neutral); }

/* Indicators */
.indicator {
    font-weight: bold;
    margin-right: 0.5rem;
}

.indicator.high { color: var(--danger); }
.indicator.low { color: var(--warning); }
.indicator.balanced { color: var(--success); }

/* Matchup cells */
.matchup-cell {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
}

.matchup-good { color: var(--success); }
.matchup-bad { color: var(--danger); }
.matchup-rate {
    color: var(--text-secondary);
    font-size: 0.8rem;
}

/* Run info */
.run-info {
    background: var(--bg-card);
    border-radius: 8px;
    padding: 1.5rem;
    border: 1px solid var(--border-color);
}

.run-info h3 {
    margin-bottom: 1rem;
    color: var(--text-primary);
}

.run-info p {
    margin-bottom: 0.5rem;
    color: var(--text-secondary);
}

.run-info strong {
    color: var(--text-primary);
}

/* Footer */
.report-footer {
    background: var(--bg-secondary);
    padding: 1.5rem 2rem;
    text-align: center;
    color: var(--text-secondary);
    font-size: 0.85rem;
    border-top: 1px solid var(--border-color);
    margin-top: 2rem;
}

/* Responsive */
@media (max-width: 768px) {
    .report-header {
        flex-direction: column;
        gap: 1rem;
        text-align: center;
    }

    .header-meta {
        text-align: center;
    }

    .tabs {
        overflow-x: auto;
        padding: 0 1rem;
    }

    .tab-btn {
        padding: 0.75rem 1rem;
        white-space: nowrap;
    }

    .content {
        padding: 1rem;
    }

    .metric-card.wide {
        grid-column: span 1;
    }
}
"""

    def _get_js(self) -> str:
        """Get the JavaScript for the report."""
        return """// Essence Wars Report JavaScript

document.addEventListener('DOMContentLoaded', function() {
    // Tab switching
    const tabBtns = document.querySelectorAll('.tab-btn');
    const tabPanels = document.querySelectorAll('.tab-panel');

    tabBtns.forEach(btn => {
        btn.addEventListener('click', function() {
            const tabId = this.dataset.tab;

            // Update active states
            tabBtns.forEach(b => b.classList.remove('active'));
            tabPanels.forEach(p => p.classList.remove('active'));

            this.classList.add('active');
            document.getElementById(tabId + '-panel').classList.add('active');

            // Trigger Plotly resize for charts that might be in the newly visible tab
            window.dispatchEvent(new Event('resize'));
        });
    });

    // Make tables sortable
    const tables = document.querySelectorAll('.deck-table');
    tables.forEach(table => {
        const headers = table.querySelectorAll('th');
        headers.forEach((header, index) => {
            header.style.cursor = 'pointer';
            header.addEventListener('click', () => sortTable(table, index));
        });
    });
});

function sortTable(table, columnIndex) {
    const tbody = table.querySelector('tbody');
    const rows = Array.from(tbody.querySelectorAll('tr'));

    // Determine sort direction
    const currentDir = table.dataset.sortDir === 'asc' ? 'desc' : 'asc';
    table.dataset.sortDir = currentDir;
    table.dataset.sortCol = columnIndex;

    rows.sort((a, b) => {
        const aVal = a.cells[columnIndex].textContent.trim();
        const bVal = b.cells[columnIndex].textContent.trim();

        // Try numeric comparison first
        const aNum = parseFloat(aVal.replace(/[^0-9.-]/g, ''));
        const bNum = parseFloat(bVal.replace(/[^0-9.-]/g, ''));

        if (!isNaN(aNum) && !isNaN(bNum)) {
            return currentDir === 'asc' ? aNum - bNum : bNum - aNum;
        }

        // Fall back to string comparison
        return currentDir === 'asc'
            ? aVal.localeCompare(bVal)
            : bVal.localeCompare(aVal);
    });

    // Re-append sorted rows
    rows.forEach(row => tbody.appendChild(row));
}
"""
